# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory
WORKDIR /<%= name %>

# Install UV
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Copy the application code
COPY . .

# Create a virtual environment
RUN uv venv

# Activate the virtual environment and install dependencies
RUN .venv/bin/activate && uv pip install .

# Specify the command to run the application
CMD ["sh", "-c", ".venv/bin/activate && python app.py"]
